[project]
name = "password-generator"
version = "0.1.0"
description = "A simple password generator web app"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.43.0",
]
