[project]
name = "15_stateful_chatbot_authentication"
version = "0.1.0"
description = "Stateful Chatbot with GitHub Authentication"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chainlit>=2.4.1",
    "google-generativeai>=0.8.4",
    "python-dotenv>=1.0.1",
]
