[project]
name = "todo-cli"
version = "0.1.0"
description = "A simple command-line To-Do List Manager built with Python and Click, managed using UV package manager."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.8",
]
